### ISSUE TITLE
Create Visualization Plot

### ISSUE THREAD

**Issue by hepaces89** [laurathepluralized/multi-agent-data-analysis#4]
Create the Plot for the visualization tab

Requires:
- [ ] a string indicating the target column name (the y variable) - pending Hubert
- [ ] A list of potential  X variables - pending Hubert

Will need to:
- [x] allow for the selection of a primary "X variable"
- [x] allow for the restriction of non-primary "X variables"
     - continuous variables will be restricted by range
        - [x] select value
        - [x] have it affect output
     - categorical variables will be selected by multiple selection drop downs
        - [x] select value
        - [x] have it affect output
- [x] Plot the Y variable against the X variable
     - [x] Continuous X variables will be plotted as a scatter plot
     - [x] Categorical Y variables will be plotted as a boxplot

**Comment by laurathepluralized** [comment]
I might leave the bar chart as future work. I'm having enough trouble just getting the non-selected X variables to dynamically allow me to fix them as it is; dynamically changing plot types sounds totally impossible at the moment. Editing description.
Also, @hepaces89 , I know you're busy, but getting the target column name and potential x column names would be a huge help! Right now I have hardcoded names in lists :(

**Comment by gtcooke94** [comment]
Dynamically plotting with the fixed values.
Issue left - if there's no data an error message will pop up. This could be cleaner but does't seem super high priority.
For example, vel_max_predator = 40 only has allow_prey_switching_t_2_predator as True, so if that is set to False with vel_max_predator as 40 in the dropdowns there will be no data to plot.
