### ISSUE TITLE
Stability Analysis Tab

### ISSUE THREAD

**Issue by hepaces89** [laurathepluralized/multi-agent-data-analysis#6]
Build the Stability Analysis Tab

This tab will execute the stability analysis algorithm and display the results

Requires:

- [x] Stability Function - Done use "runStablilityCheck()" from https://github.com/laurathepluralized/multi-agent-data-analysis/blob/master/shinyApp/analysis.R

Context:
 - the data

Inputs:
- [x] List of X variables
- [x] the Y variable

Output:
- [x] The stability analysis results as a table

**Comment by knachary** [comment]
I am still looking at this, unless Hubert you already have something that is working. I

**Comment by hepaces89** [comment]
I had something working on Sunday, but likely its been broken since, so carry on :)

**Comment by hepaces89** [comment]
this is the code that was working earlier:

`  output$stabilityAnalysis <- renderTable({
    # input$file1 will be NULL initially. After the user selects
    # and uploads a file, head of that data file by default,
    # or all rows if selected, will be shown.
    
    if(input$runStability){
      req(input$file1)
      
      df <- read.csv(input$file1$datapath,
                     header = input$header,
                     sep = input$sep,
                     quote = input$quote)
      
      result_col <- input$result_col
      numericCol <- c("vel_max.t.1",
                      "vel_max.predator",
                      "pitch_rate_max.predator",
                      "turn_rate_max.predator")
      categoryCol <- c("team_id",
                       "allow_prey_switching.t.2.predator")
      
      stabilityResults <- runStablilityCheck(df, result_col, numericCol, categoryCol)
      
      return(stabilityResults)
    }`

**Comment by hepaces89** [comment]
`stabilityResults <- runStablilityCheck(df, result_col, numericCol, categoryCol)`

is the point where the stability analysis code is run.

**Comment by hepaces89** [comment]
ported over Kartik's code into a separate module and hooked it up to the csv file
